import os
import logging
from dotenv import load_dotenv

load_dotenv()

LOG_LEVEL = logging.DEBUG
DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
DISCORD_NAME = 'Test'
WELCOME = 'welcome'
APPLICATIONS = 'applications'
DISCORD_CHANNELS = [(WELCOME, None), (APPLICATIONS, None)]
ADMIN_ROLE = 'Administrators'
NOT_APPLIED_ROLE = 'Not Applied'
ADMIN_PASSWORD = os.getenv('ADMIN_PASSWORD')
RCON_IP = os.getenv('RCON_IP')
RCON_PORT = int(os.getenv('RCON_PORT'))
PREFIX = '!'
SPREADSHEET_ID = os.getenv('SPREADSHEET_ID')
APPLICATION_SHEET_ID = os.getenv('APPLICATION_SHEET_ID')
STEAMID_QUESTION = 9
APL = {}
GREETING_RANGE = 'Apps!C2'
APPLIED_RANGE = 'Apps!C3'
FINISHED_RANGE = 'Apps!C4'
COMMITED_RANGE = 'Apps!C5'
ACCEPTED_RANGE = 'Apps!C6'
REJECTED_RANGE = 'Apps!C7'
WHITELISTING_FAILED_RANGE = 'Apps!C8'
WHITELISTING_SUCCEEDED_RANGE = 'Apps!C9'
APP_CLOSED_RANGE = 'Apps!C10'
QUESTIONS_RANGE = 'Apps!A2:A'
